name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1.2

      # Install Tools
      - name: Install Tools
        run: |
          sudo apt-get install wget build-essential python3 ninja-build
          pip3 install setuptools
          pip3 install requests
          pip3 install pexpect
          pip3 install meson

      # Install (n)Migen / LiteX / Cores
      - name: Install LiteX
        run: |
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          python3 litex_setup.py --init --install --user

      # Install RISC-V GCC
      - name: Install RISC-V GCC
        run: |
          sudo python3 litex_setup.py --gcc=riscv

      # Install Project
      - name: Install Project
        run: python3 setup.py develop --user

      # Test
      - name: Run Tests
        run: |
          python3 setup.py test
